[workspace]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
authors = ["skymrp project contributors"]
homepage = "https://skymrp.org/"

[package]
name = "skymrp"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
homepage = { workspace = true }

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "skymrp"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
cc = "1.0.77"
cmake = "0.1.49"
rusty-hook = "0.11.2"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock"] }
encoding_rs = "0.8"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
sdl2 = { version = "0.38.0", features = ["bundled", "static-link", "unsafe_textures"] }
sdl2-sys = "0.38.0"
skymrp_dynarmic_wrapper = { path = "src/cpu/dynarmic_wrapper" }
skymrp_sonivox_wrapper = { path = "src/audio/sonivox_wrapper" }

[build-dependencies]
cc = { workspace = true }
cmake = { workspace = true }
rusty-hook = { workspace = true }
