name: Build skymrp

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always
  BOOST_URL: https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Boost
        run: brew install boost

      - name: Build
        run: cargo build --release

      - name: Prepare release files
        run: scripts/prepare-release.sh --prepare-files

      - name: Create release zip
        run: |
          output="skymrp_${GITHUB_REF_NAME}_macOS_aarch64.zip"
          scripts/prepare-release.sh --create-zip target/release/skymrp -o "$output"
          echo "ASSET_NAME=$output" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-macos
          path: ${{ env.ASSET_NAME }}

  build-windows:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install zip
        run: choco install zip -y

      - name: Download Boost
        run: curl -L -o boost_1_81_0.7z "$BOOST_URL"

      - name: Extract Boost
        run: |
          7z -ovendor x boost_1_81_0.7z
          mv vendor/boost_1_81_0 vendor/boost

      - name: Build
        run: cargo build --release

      - name: Prepare release files
        run: scripts/prepare-release.sh --prepare-files

      - name: Create release zip
        run: |
          output="skymrp_${GITHUB_REF_NAME}_Windows_x86_64.zip"
          scripts/prepare-release.sh --create-zip target/release/skymrp.exe -o "$output"
          echo "ASSET_NAME=$output" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-windows
          path: ${{ env.ASSET_NAME }}

  build-linux:
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            arch: x86_64
          - runner: ubuntu-24.04-arm
            arch: aarch64

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libboost-all-dev

      - name: Build
        run: cargo build --release

      - name: Prepare release files
        run: scripts/prepare-release.sh --prepare-files

      - name: Create release zip
        run: |
          output="skymrp_${GITHUB_REF_NAME}_Linux_${{ matrix.arch }}.zip"
          scripts/prepare-release.sh --create-zip target/release/skymrp -o "$output"
          echo "ASSET_NAME=$output" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-linux-${{ matrix.arch }}
          path: ${{ env.ASSET_NAME }}

  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download Boost
        run: curl -L -o boost_1_81_0.7z "$BOOST_URL"

      - name: Extract Boost
        run: |
          7z -ovendor x boost_1_81_0.7z
          mv vendor/boost_1_81_0 vendor/boost

      - name: Install AArch64 Android Rust toolchain
        run: rustup target add aarch64-linux-android

      - name: Install cargo-ndk
        run: cargo install cargo-ndk@3.5.4

      - name: Download Gradle
        run: curl -L -o gradle-8.11.1-bin.zip "https://services.gradle.org/distributions/gradle-8.11.1-bin.zip"

      - name: Extract Gradle
        run: 7z -ogradle x gradle-8.11.1-bin.zip

      - name: Download Android NDK
        run: curl -L -o android-ndk-r25c-linux.zip "https://dl.google.com/android/repository/android-ndk-r25c-linux.zip"

      - name: Extract Android NDK
        run: 7z -oandroid-ndk -snld x android-ndk-r25c-linux.zip

      - name: Link Android NDK
        run: ln -s $PWD'/android-ndk/android-ndk-r25c' $ANDROID_SDK_ROOT'/ndk/25.2.9519653'

      - name: Generate local.properties file
        run: echo 'sdk.dir='$ANDROID_SDK_ROOT > android/local.properties

      # Don't attempt to run tests (can't run on Android).
      - name: Build for Android
        run: cd android && ../gradle/gradle-8.11.1/bin/gradle assembleRelease && mv app/build/outputs/apk/release/app-release.apk ../SkyMRP.apk
        env:
          # The version should match the ndkVersion defined in `android\app\build.gradle`
          ANDROID_NDK_ROOT: '/usr/local/lib/android/sdk/ndk/25.2.9519653'
          ANDROID_NDK: '/usr/local/lib/android/sdk/ndk/25.2.9519653'
          ANDROID_NDK_HOME: '/usr/local/lib/android/sdk/ndk/25.2.9519653'

      - name: Prepare release files
        run: scripts/prepare-release.sh --prepare-files

      - name: Create release zip
        run: |
          output="SkyMRP_${GITHUB_REF_NAME}_Android_AArch64.zip"
          scripts/prepare-release.sh --create-zip SkyMRP.apk -o "$output"
          echo "ASSET_NAME=$output" >> "$GITHUB_ENV"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-android
          path: ${{ env.ASSET_NAME }}

  release:
    runs-on: ubuntu-latest
    needs:
      - build-macos
      - build-windows
      - build-linux
      - build-android

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: artifact-*
          merge-multiple: true

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          artifacts: "artifacts/*.zip"
